# Generated by Django 3.0.8 on 2020-07-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_locationmodel_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'Location'},
        ),
    ]
