# Generated by Django 3.0.8 on 2020-07-26 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200726_1204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_auto_20200726_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='product',
            field=models.ManyToManyField(to='shop.ProductModel'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
