# Generated by Django 3.0.8 on 2020-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20200716_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewedmodel',
            name='user_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
