# Generated by Django 3.0.8 on 2020-07-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_objectviewedmodel_user_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewedmodel',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Product viewed', 'verbose_name_plural': 'Products viewed'},
        ),
    ]
