# Generated by Django 3.0.8 on 2020-07-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20200716_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewedmodel',
            options={'ordering': ['-created'], 'verbose_name': 'Product viewed', 'verbose_name_plural': 'Products viewed'},
        ),
        migrations.RenameField(
            model_name='objectviewedmodel',
            old_name='timestamp',
            new_name='created',
        ),
    ]
