# Generated by Django 3.0.8 on 2020-07-26 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='payment',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='payment',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
