# Generated by Django 3.0.8 on 2020-07-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default=1, max_length=225, verbose_name='Nom & prénoms'),
            preserve_default=False,
        ),
    ]
