# Generated by Django 3.0.8 on 2020-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Nom & prénoms'),
        ),
    ]
