# Generated by Django 3.1 on 2020-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200731_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='First & Last Name'),
        ),
    ]
