# Generated by Django 3.0.8 on 2020-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailactivationmodel_guestemailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivationmodel',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
