# Generated by Django 3.0.8 on 2020-07-05 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to=shop.models.product, verbose_name='Image_1')),
                ('img2', models.ImageField(blank=True, upload_to=shop.models.product, verbose_name='Image_2')),
                ('img3', models.ImageField(blank=True, upload_to=shop.models.product, verbose_name='Image_3')),
                ('img4', models.ImageField(blank=True, upload_to=shop.models.product, verbose_name='Image_4')),
                ('img5', models.ImageField(blank=True, upload_to=shop.models.product, verbose_name='Image_5')),
            ],
            options={
                'verbose_name': 'Image de description',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200, unique=True, verbose_name='catégorie principale')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('img', models.ImageField(upload_to=shop.models.category, verbose_name='Image de description')),
            ],
            options={
                'verbose_name': 'catégorie principale',
                'verbose_name_plural': 'catégories principales',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('imagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.ImageModel')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom')),
                ('label', models.CharField(blank=True, choices=[('N', 'New'), ('S', 'Sale')], max_length=1)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de location')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('rent_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date mise en location')),
                ('keywords', models.CharField(help_text='Ensemble de mots-clés SEO', max_length=255, verbose_name='Mot clés')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Date ajout')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Date mise à jour')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('-pub_date',),
            },
            bases=('shop.imagemodel',),
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='sous-categorie')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('keywords', models.CharField(blank=True, help_text='Ensemble de mots-clés SEO', max_length=200, verbose_name='Mots clés')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.MainCategoryModel', verbose_name='catégorie principale')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WishListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel')),
            ],
            options={
                'verbose_name': 'Liste de souhaits',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse email')),
                ('comment', models.TextField(verbose_name='Votre commentaire sur le produit')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('rating', models.CharField(blank=True, max_length=2, verbose_name='notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryModel', verbose_name='sous-catégorie'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
