# Generated by Django 3.0.7 on 2020-06-28 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Url')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date ajout')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date mise à jour')),
                ('img1', models.ImageField(blank=True, upload_to=shop.models.rename, verbose_name='IMG1')),
                ('img2', models.ImageField(blank=True, upload_to=shop.models.rename, verbose_name='IMG2')),
                ('img3', models.ImageField(upload_to=shop.models.rename, verbose_name='IMG3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
