# Generated by Django 3.0.8 on 2020-07-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('price', '-pub_date'), 'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
    ]
