# Generated by Django 3.0.8 on 2020-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Nombre de vues'),
        ),
    ]
