# Generated by Django 3.0.8 on 2020-07-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ('name',), 'verbose_name': 'sub-category'},
        ),
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
    ]
