# Generated by Django 3.0.8 on 2020-07-30 16:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200730_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='product'),
            preserve_default=False,
        ),
    ]
