# Generated by Django 3.0.8 on 2020-07-21 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200721_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ('-date',), 'verbose_name': 'review'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='label',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale')], max_length=4),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='name',
            field=models.CharField(blank=True, default='anonyme', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(blank=True, max_length=2, verbose_name='rate'),
        ),
    ]
