# Generated by Django 3.0.7 on 2020-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200702_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='rent_date',
            field=models.DateField(verbose_name='Date mise en location'),
        ),
    ]
