# Generated by Django 3.0.7 on 2020-06-29 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200628_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='categorie')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to=shop.models.rename, verbose_name='Image_1')),
                ('img2', models.ImageField(blank=True, upload_to=shop.models.rename, verbose_name='Image_2')),
                ('img3', models.ImageField(blank=True, upload_to=shop.models.rename, verbose_name='Image_3')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('imagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.ImageModel')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Url')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date ajout')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date mise à jour')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryModel', verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('-pub_date',),
            },
            bases=('shop.imagemodel',),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
