# Generated by Django 3.0.8 on 2020-07-16 17:34

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200714_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeaturedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=shop.models.image_upload_to_featured)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('desc', models.TextField(blank=True, max_length=225, null=True)),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductSlider',
        ),
    ]
