# Generated by Django 3.0.7 on 2020-06-30 14:20

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200629_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='img4',
            field=models.ImageField(blank=True, upload_to=shop.models.rename, verbose_name='Image_4'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='img5',
            field=models.ImageField(blank=True, upload_to=shop.models.rename, verbose_name='Image_5'),
        ),
    ]
