# Generated by Django 3.0.8 on 2020-07-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200716_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.DeleteModel(
            name='ProductFeaturedModel',
        ),
    ]
