# Generated by Django 3.0.7 on 2020-07-02 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200702_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='rent_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date mise en location'),
        ),
    ]
