# Generated by Django 3.0.8 on 2020-07-30 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='img_1',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='img_2',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='img_3',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='img_4',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='product'),
            preserve_default=False,
        ),
    ]
