# Generated by Django 3.0.8 on 2020-07-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200721_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'verbose_name': 'Product Image'},
        ),
        migrations.RemoveField(
            model_name='productimagemodel',
            name='position',
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel'),
        ),
    ]
