# Generated by Django 3.0.8 on 2020-07-21 16:13

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200721_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='img',
            field=models.ImageField(blank=True, upload_to=shop.models.product_image_upload),
        ),
    ]
