# Generated by Django 3.0.7 on 2020-07-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200702_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de location'),
        ),
    ]
