# Generated by Django 3.0.8 on 2020-08-01 01:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200730_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategorymodel',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='p_image_1'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img_1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='p_image_2'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img_2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='p_image_3'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img_3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='p_image_4'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img_4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='p_image_5'),
        ),
    ]
