# Generated by Django 3.0.8 on 2020-07-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200716_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'verbose_name': 'Liste de souhait'},
        ),
    ]
