# Generated by Django 3.0.8 on 2020-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200721_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
    ]
