# Generated by Django 3.0.7 on 2020-07-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200702_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Url'),
        ),
    ]
