# Generated by Django 3.0.8 on 2020-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200716_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ('name',), 'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='maincategorymodel',
            options={'ordering': ('name',), 'verbose_name': 'catégorie principale'},
        ),
        migrations.AlterField(
            model_name='maincategorymodel',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='catégorie principale'),
        ),
    ]
