# Generated by Django 3.0.7 on 2020-07-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200702_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Image de description'},
        ),
    ]
