# Generated by Django 3.0.8 on 2020-07-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200721_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='label',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('HOT', 'HOT')], max_length=4),
        ),
    ]
