# Generated by Django 3.0.8 on 2020-07-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200722_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='keywords',
        ),
    ]
