# Generated by Django 3.0.8 on 2020-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200723_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
    ]
