# Generated by Django 3.0.8 on 2020-07-25 15:28

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200724_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategorymodel',
            name='img',
            field=models.ImageField(blank=True, upload_to=shop.models.category),
        ),
    ]
