# Generated by Django 3.0.8 on 2020-07-26 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200725_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='keywords',
            field=models.CharField(blank=True, help_text='Ensemble de mots-clés SEO', max_length=200, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='sub-category'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(to='shop.CategoryModel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='pub date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='rent_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date rent'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='updated',
            field=models.DateField(auto_now_add=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='views'),
        ),
    ]
