# Generated by Django 3.0.8 on 2020-07-30 15:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=255, verbose_name='Full Name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('address_delivery', models.CharField(blank=True, max_length=120, verbose_name='Adresse delivery (optionnelle)')),
                ('address_type', models.CharField(choices=[('billing', 'Billing address'), ('shipping', 'Shipping address'), ('bank transfer', 'Direct bank transfer')], max_length=120)),
                ('postal_code', models.CharField(max_length=255, verbose_name='Code postal')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel')),
            ],
        ),
    ]
