# Generated by Django 3.0.8 on 2020-07-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
        ),
    ]
