# Generated by Django 3.0.8 on 2020-07-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200724_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='full_name',
            field=models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=255, null=True, verbose_name='Nom & prénoms'),
        ),
    ]
