# Generated by Django 3.0.8 on 2020-07-26 12:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200724_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='postal_code',
            field=models.CharField(default=12, max_length=255, verbose_name='Code postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address_delivery',
            field=models.CharField(max_length=120, verbose_name='Adresse delivery'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='full_name',
            field=models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note (optionnelle)'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
