# Generated by Django 3.0.8 on 2020-07-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('address', '0004_auto_20200726_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='full_name',
            field=models.CharField(blank=True, default=1, help_text='Shipping to? Who is it for?', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentModel'),
        ),
    ]
