# Generated by Django 3.0.8 on 2020-07-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200726_1353'),
        ('address', '0005_auto_20200726_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='payment',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
            preserve_default=False,
        ),
    ]
