# Generated by Django 3.0.8 on 2020-07-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200727_1950'),
        ('address', '0007_auto_20200726_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='note',
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address_delivery',
            field=models.CharField(blank=True, max_length=120, verbose_name='Adresse delivery (optionnelle)'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
        ),
    ]
