# Generated by Django 3.0.8 on 2020-07-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('shop', '0001_initial'),
        ('address', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, verbose_name='ID commande')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Mise à jour')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='address.AddressModel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.LocationModel')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentModel')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='address.AddressModel')),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.CreateModel(
            name='OrderPurchaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrdersModel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel')),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['-created', '-updated'],
            },
        ),
    ]
