# Generated by Django 3.0.8 on 2020-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersmodel',
            options={'ordering': ('-updated', '-created'), 'verbose_name': 'Order'},
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='billing_address_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='shipping_address_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=100),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID Order'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
    ]
