# Generated by Django 3.0.8 on 2020-07-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200716_2021'),
        ('location', '0001_initial'),
        ('payment', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPurchaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='ordersmodel',
            options={'ordering': ('-updated', '-created'), 'verbose_name': 'Commande'},
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='apartement',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='note',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.LocationModel'),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentModel'),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120),
        ),
        migrations.DeleteModel(
            name='ItemOrderModel',
        ),
        migrations.AddField(
            model_name='orderpurchasemodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrdersModel'),
        ),
        migrations.AddField(
            model_name='orderpurchasemodel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
        ),
        migrations.AddField(
            model_name='orderpurchasemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel'),
        ),
    ]
