# Generated by Django 3.0.8 on 2020-07-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='customer',
        ),
    ]
