# Generated by Django 3.0.8 on 2020-07-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200712_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='apartement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Appartement (optionnel)'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entreprise (optionnel)'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='zipcode',
            field=models.CharField(max_length=255, verbose_name='Code postal/ZIP'),
        ),
    ]
