# Generated by Django 3.0.8 on 2020-07-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_ordersmodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
