# Generated by Django 3.0.8 on 2020-07-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200726_1204'),
        ('orders', '0002_auto_20200726_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.LocationModel'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
