# Generated by Django 3.0.8 on 2020-07-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersmodel_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID commande'),
        ),
    ]
