# Generated by Django 3.0.8 on 2020-07-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200712_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='order_id',
        ),
    ]
