# Generated by Django 3.0.8 on 2020-07-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200726_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpurchasemodel',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Order'},
        ),
    ]
