# Generated by Django 3.0.8 on 2020-07-06 13:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200705_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Téléphone'),
        ),
    ]
