# Generated by Django 3.0.8 on 2020-07-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20200726_1353'),
        ('orders', '0005_auto_20200726_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='billing_address',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='address.AddressModel'),
            preserve_default=False,
        ),
    ]
