# Generated by Django 3.0.8 on 2020-07-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20200726_1353'),
        ('orders', '0006_auto_20200726_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='address.AddressModel'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='address.AddressModel'),
        ),
    ]
