# Generated by Django 3.0.8 on 2020-07-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200726_1411'),
        ('location', '0004_auto_20200726_1353'),
        ('shop', '0013_auto_20200726_1204'),
        ('orders', '0007_auto_20200726_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpurchasemodel',
            name='order',
        ),
        migrations.AddField(
            model_name='orderpurchasemodel',
            name='order_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpurchasemodel',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
        ),
        migrations.AlterField(
            model_name='orderpurchasemodel',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.LocationModel'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentModel'),
        ),
    ]
